# Generated by Django 4.2.3 on 2023-07-16 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='field',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
