# Generated by Django 4.2.3 on 2023-07-16 14:30

from django.db import migrations, models
import final_project.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('useful_materials', '0003_alter_materials_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='materials_files/', validators=[final_project.core.validators.file_size_validator]),
        ),
    ]
