# Generated by Django 4.2.3 on 2026-04-03 13:58

from django.db import migrations, models
import final_project.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_completed_early_count_and_more'),
        ('useful_materials', '0004_alter_materials_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='field',
        ),
        migrations.AddField(
            model_name='materials',
            name='specializations',
            field=models.ManyToManyField(related_name='materials', to='accounts.specialization'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='materials_files/', validators=[final_project.core.validators.file_size_validator, final_project.core.validators.pdf_only_validator]),
        ),
    ]
