# Generated by Django 4.2.3 on 2026-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_materials', '0006_materialcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='reference_is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materials',
            name='reference_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='reference_validation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
