# Generated by Django 4.2.3 on 2026-04-15 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useful_materials', '0007_materials_reference_is_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='useful_materials.materialcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='materialcommentvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_material_comment_vote'),
        ),
    ]
