# Generated by Django 4.2.3 on 2026-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='completed_early_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='completed_on_time_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='late_unassignments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='trust_score',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='unassignments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
