# Generated by Django 4.2.3 on 2026-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_completed_early_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('reviewer', 'reviewer')], max_length=8),
        ),
    ]
