# Generated by Django 4.2.3 on 2023-07-14 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator])),
                ('subject', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('death_line', models.DateField()),
                ('price_cap', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.FileField(upload_to='term_paper_files/')),
            ],
        ),
    ]
