# Generated by Django 4.2.3 on 2023-07-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import final_project.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term_papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termpaper',
            name='is_taken',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='termpaper',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termpaper',
            name='content',
            field=models.FileField(upload_to='term_paper_files/', validators=[final_project.core.validators.file_size_validator]),
        ),
    ]
