# Generated by Django 4.2.3 on 2023-07-14 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term_papers', '0003_rename_user_id_termpaper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='termpaper',
            name='taken_by',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.RESTRICT, related_name='taken_by_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
