# Generated by Django 4.2.3 on 2023-07-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term_papers', '0004_termpaper_taken_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termpaper',
            name='taken_by',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='taken_by_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
