# Generated by Django 4.2.3 on 2023-07-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_papers', '0005_alter_termpaper_taken_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termpaper',
            name='is_taken',
        ),
    ]
