# Generated by Django 4.2.3 on 2023-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_papers', '0007_termpaper_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='termpaper',
            name='rated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
