# Generated by Django 4.2.3 on 2026-03-15 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term_papers', '0011_alter_termpaper_taken_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermPaperRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_term_paper_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_term_paper_requests', to=settings.AUTH_USER_MODEL)),
                ('term_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='term_papers.termpaper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='termpaperrequest',
            constraint=models.UniqueConstraint(fields=('term_paper', 'teacher'), name='unique_teacher_request_per_term_paper'),
        ),
    ]
