# Generated by Django 4.2.3 on 2026-04-03 13:58

from django.db import migrations, models
import final_project.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('term_papers', '0012_termpaperrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termpaper',
            name='content',
            field=models.FileField(upload_to='term_paper_files/', validators=[final_project.core.validators.file_size_validator, final_project.core.validators.pdf_only_validator]),
        ),
    ]
