# Generated by Django 4.2.3 on 2026-03-21 16:49

from django.db import migrations, models
import final_project.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image (max 2 MB).', null=True, upload_to='lesson_covers/', validators=[final_project.core.validators.file_size_validator]),
        ),
    ]
