# Generated by Django 4.2.3 on 2026-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_completed_early_count_and_more'),
        ('lessons', '0002_lesson_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='specializations',
            field=models.ManyToManyField(related_name='lessons', to='accounts.specialization'),
        ),
    ]
