# Generated by Django 4.2.3 on 2023-07-16 12:20

import django.core.validators
from django.db import migrations, models
import final_project.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('subject', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('content', models.FileField(upload_to='term_paper_files/', validators=[final_project.core.validators.file_size_validator])),
                ('rating', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
