# Generated by Django 4.2.3 on 2023-07-16 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('completed_papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedpaper',
            name='rating',
        ),
        migrations.AddField(
            model_name='completedpaper',
            name='completed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
