# Generated by Django 4.2.3 on 2026-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_specializations'),
        ('completed_papers', '0006_alter_completedpaper_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedpaper',
            name='subject',
        ),
        migrations.AddField(
            model_name='completedpaper',
            name='specializations',
            field=models.ManyToManyField(related_name='completed_papers', to='accounts.specialization'),
        ),
    ]
