# Generated by Django 4.2.3 on 2026-03-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_papers', '0007_remove_completedpaper_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
