# Generated by Django 4.2.3 on 2023-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='rate',
            field=models.PositiveIntegerField(blank=True, choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default=0),
        ),
    ]
