# Generated by Django 4.2.3 on 2023-08-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0004_alter_trophy_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name_plural': 'Trophies'},
        ),
    ]
