# Generated by Django 4.2.3 on 2026-03-28 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0005_alter_trophy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(155)]),
        ),
    ]
